api/urls.py
from django.urls import path, include

from . import views

urlpatterns = [	
	path("v1/productos", views.ProductoList.as_view(), name="producto_list"),
	path("v1/productos/<str:codigo>", views.ProductoDetalle.as_view(), name="producto_detalle"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
	path('', views.Home.as_view(), name="home"),
	path('login/', 
		auth_views.LoginView.as_view(template_name = "bases/login.html"), 
		name="login"),
	path('logout/', 
		auth_views.LogoutView.as_view(template_name = "bases/login.html"), 
		name="logout"),
	path('sin_privilegios/', 
		views.HomeSinPrivilegios.as_view(), 
		name="sin_privilegios")
]

cmp/urls.py
from django.urls import path, include

from . import views, reports

urlpatterns = [	
	path("proveedores/", views.ProveedorView.as_view(), name = "proveedor_list"),
	path("proveedores/create", views.ProveedorCreate.as_view(), name = "proveedor_create"),
	path("proveedores/edit/<int:pk>", views.ProveedorUpdateView.as_view(), name = "proveedor_edit"),
	path("proveedores/inactivar/<int:id>", views.proveedorDeleteView, name = "proveedor_inactivar"),

	path("compras/", views.ComprasView.as_view(), name = "compras_list"),
	path("compras/create", views.CreateCompra, name = "compras_create"),
	path("compras/edit/<int:id>", views.CreateCompra, name = "compras_edit"),
	path("compras/<int:compra_id>/delete/<int:pk>", views.CompraDetDelete.as_view(), name = "compras_delete"),

	path("compras/lists", reports.reporte_compras, name="compras_print_all"),
	path("compras/<int:compra_id>/imprimir", reports.imprimir_compra, name="compras_print_one"),
]

fac/urls.py
from django.urls import path, include

from . import views
from .reports import imprimirFacturaRecibo, imprimirFacturaList

urlpatterns = [	
	path("clientes/", views.ClienteView.as_view(), name = "cliente_list"),
	path("clientes/create", views.ClienteCreate.as_view(), name = "cliente_create"),
	path("clientes/edit/<int:pk>", views.ClienteUpdate.as_view(), name = "cliente_edit"),
	path("clientes/inactivar/<int:id>", views.clienteDelete, name = "cliente_inactivar"),

	path("facturas/", views.FacturaView.as_view(), name = "factura_list"),
	path("facturas/create", views.facturas, name = "factura_create"),
	path("facturas/edit/<int:id>", views.facturas, name = "factura_edit"),
	path("facturas/buscar_producto", views.FacProductoView.as_view(), name = "factura_producto"),
	path("facturas/borrar_detalle/<int:id>", views.borrarDetalleFactura, name = "factura_delete"),
	
	path("facturas/imprimir/<int:id>", imprimirFacturaRecibo, name = "factura_imprimir1"),
	
	path("facturas/imprimir_all/<str:f1>/<str:f2>", imprimirFacturaList, name = "facturas_imprimir_all"),

]

inv/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path("categorias/", views.CategoriaView.as_view(), name = "categoria_list"),
	path("categorias/create", views.CategoriaCreate.as_view(), name = "categoria_create"),
	path("categorias/edit/<int:pk>", views.CategoriaUpdateView.as_view(), name = "categoria_edit"),
	path("categorias/delete/<int:pk>", views.CategoriaDeleteView.as_view(), name = "categoria_delete"),

	path("subcategorias/", views.SubCategoriaView.as_view(), name = "subcategoria_list"),
	path("subcategorias/create", views.SubCategoriaCreate.as_view(), name = "subcategoria_create"),
	path("subcategorias/edit/<int:pk>", views.SubCategoriaUpdateView.as_view(), name = "subcategoria_edit"),
	path("subcategorias/delete/<int:pk>", views.SubCategoriaDeleteView.as_view(), name = "subcategoria_delete"),

	path("marcas/", views.MarcaView.as_view(), name = "marca_list"),
	path("marcas/create", views.MarcaCreate.as_view(), name = "marca_create"),
	path("marcas/edit/<int:pk>", views.MarcaUpdateView.as_view(), name = "marca_edit"),
	path("marcas/inactivar/<int:id>", views.marca_inactivar, name = "marca_inactivar"),

	path("um/", views.UMView.as_view(), name = "um_list"),
	path("um/create", views.UMCreate.as_view(), name = "um_create"),
	path("um/edit/<int:pk>", views.UMUpdateView.as_view(), name = "um_edit"),
	path("um/inactivar/<int:id>", views.um_inactivar, name = "um_inactivar"),

	path("producto/", views.ProductoView.as_view(), name = "producto_list"),
	path("producto/create", views.ProductoCreate.as_view(), name = "producto_create"),
	path("producto/edit/<int:pk>", views.ProductoUpdateView.as_view(), name = "producto_edit"),
	path("producto/inactivar/<int:id>", views.producto_inactivar, name = "producto_inactivar"),

]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %} Sistema de Compra e Inventario {% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this page -->
  <link href=" {% static 'base/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

  {# use alertify #}
  <link href="{% static 'base/vendor/alertify/css/themes/bootstrap.rtl.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'base/vendor/alertify/css/alertify.css' %}" rel="stylesheet" type="text/css">

  {# use datetimepicker #}
  <link href="{% static 'base/css/jquery-datetimepicker.min.css' %}" rel="stylesheet" type="text/css">

  {# use bootstrap table #}
  <link href="{% static 'base/css/bootstrap-table.min.css' %}" rel="stylesheet" type="text/css">

  {# use select2 #}
  <link href="{% static 'base/css/select2.min.css' %}" rel="stylesheet" type="text/css">
</head>

<body id="page-top" class="bg-gradient-primary">
  <!-- Page Wrapper -->
  <div id="wrapper">
    <!-- Sidebar -->
    {% block sidebar %}
      {% include "base/sidebar.html" %}
    {% endblock %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% block topbar %}
          {% include "base/topbar.html" %}
        {% endblock %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        {% block content %}
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

        </div>
        {% endblock %}
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      {% block footer %}
        {% include "base/footer.html" %}
      {% endblock %}
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->
  {% block login %} {% endblock %}

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'bases:logout' %}">Salir</a>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="popup">
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'base/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <!-- Alertify  plugins -->  
  <script src="{% static 'base/vendor/alertify/js/alertify.min.js' %}"></script>
  <!-- Datetimepicker  plugins -->  
  <script src="{% static 'base/js/jquery-datetimepicker-full.min.js' %}"></script>
  <!-- Bootstrap Table  plugins -->  
  <script src="{% static 'base/js/bootstrap-table.min.js' %}"></script>

  <!-- Select2  plugins -->  
  <script src="{% static 'base/js/select2.min.js' %}"></script>

  <!-- Select2  plugins -->  
  <script src="{% static 'base/js/jquery-chained.min.js' %}"></script>

  {% block js %} {% endblock %}

  {% block js_modal %} 
  <script type="text/javascript">
    //para abrir el modal
    function abrir_modal(url) {
      //pedimos la url y con load() cargamos lo q nos trae la url(se hace un peticion get) y despues con una funcion cargamos el modal
      $("#popup").load(url,function(){
        $(this).modal({
          backdrop:"static",
          keyboard:false
        }); 
        $(this).modal("show");
      });
      return false;
    }

    function cerrar_modal() {
      $("#popup").modal("hide");
      return false;
    }
    {#para los mensajes #}
    {% if messages %}
      {% for message in messages %}
      //console.log("{{message.tags}}");
      if ("{{message.tags}}" == "success") {
        alertify.success("{{message}}");        
      } 
      if ("{{message.tags}}" == "error"){
        alertify.error("{{message}}");          
      }
      if ("{{message.tags}}" == "warning"){
        alertify.warning("{{message}}");          
      }
      {% endfor %}      
    {% endif %}
  </script>   
  {% endblock %}
</body>

</html>

templates/base/footer.html
<footer class="sticky-footer bg-white">
<div class="container my-auto">
  <div class="copyright text-center my-auto">
    <span>Copyright &copy; Your Website 2019</span>
  </div>
</div>
</footer>

templates/base/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'bases:home' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'bases:home' %}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard {{request.path}}</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Opciones de Menu
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item {% if request.path|slice:':5' == '/inv/' %} active {% endif %}">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Catalogos</span>
    </a>
    <div id="collapseTwo" class="collapse {% if request.path|slice:':5' == '/inv/' %} show {% endif %}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Catalogos de Inventario</h6>
        {% if perms.inv.view_categoria %}
        <a class="collapse-item" href="{% url 'inv:categoria_list' %}">Categorias</a>          
        {% endif %}
        {% if perms.inv.view_subcategoria %}
        <a class="collapse-item" href="{% url 'inv:subcategoria_list' %}">Sub-Categorias</a>
        {% endif %}
        {% if perms.inv.view_marca %}
        <a class="collapse-item" href="{% url 'inv:marca_list' %}">Marcas</a> 
        {% endif %}
        {% if perms.inv.view_unidadmedida %}
        <a class="collapse-item" href="{% url 'inv:um_list' %}">Unidades de Medidas</a> 
        {% endif %}
        {% if perms.inv.view_producto %}  
        <a class="collapse-item" href="{% url 'inv:producto_list' %}">Productos</a> 
        {% endif %}    
        <div class="collapse-divider"></div>
        {% if perms.cmp.view_proveedor %}  
        <h6 class="collapse-header">Catalogo de Compras</h6> 
        <a class="collapse-item" href="{% url 'cmp:proveedor_list' %}">Proveedores</a>   
        {% endif %}      
        <div class="collapse-divider"></div>
        {% if perms.fac.view_cliente %}  
        <h6 class="collapse-header">Catalogo de Facturación</h6> 
        <a class="collapse-item" href="{% url 'fac:cliente_list' %}">Clientes</a>   
        {% endif %}    
      </div>
    </div>
  </li>

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-truck"></i>
      <span>Movimientos</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Entradas</h6> 
        <a class="collapse-item" href="{% url 'cmp:compras_list' %}">Compras </a>   
        <h6 class="collapse-header">Salidas</h6> 
        <a class="collapse-item" href="{% url 'fac:factura_list' %}">Facturas </a>   
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

templates/base/topbar.html
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alerts Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly report is ready to download!</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-success">
              <i class="fas fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has been deposited into your account!
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-warning">
              <i class="fas fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We've noticed unusually high spending for your account.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
      </div>
    </li>

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
            <div class="status-indicator"></div>
          </div>
          <div>
            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
            <div class="small text-gray-500">Jae Chun · 1d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
            <div class="status-indicator bg-warning"></div>
          </div>
          <div>
            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div>
            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
            <div class="small text-gray-500">Chicken the Dog · 2w</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
      </div>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
        <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Cerrar Sección
        </a>
      </div>
    </li>

  </ul>

</nav>