api/urls.py
from django.urls import path, include

from . import views

urlpatterns = [	
	path("v1/productos", views.ProductoList.as_view(), name="producto_list"),
	path("v1/productos/<str:codigo>", views.ProductoDetalle.as_view(), name="producto_detalle"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

fac/urls.py
from django.urls import path, include

from . import views
from .reports import imprimirFacturaRecibo, imprimirFacturaList

urlpatterns = [	
	path("clientes/", views.ClienteView.as_view(), name = "cliente_list"),
	path("clientes/create", views.ClienteCreate.as_view(), name = "cliente_create"),
	path("clientes/edit/<int:pk>", views.ClienteUpdate.as_view(), name = "cliente_edit"),
	path("clientes/inactivar/<int:id>", views.clienteDelete, name = "cliente_inactivar"),

	path("facturas/", views.FacturaView.as_view(), name = "factura_list"),
	path("facturas/create", views.facturas, name = "factura_create"),
	path("facturas/edit/<int:id>", views.facturas, name = "factura_edit"),
	path("facturas/buscar_producto", views.FacProductoView.as_view(), name = "factura_producto"),
	path("facturas/borrar_detalle/<int:id>", views.borrarDetalleFactura, name = "factura_delete"),
	
	path("facturas/imprimir/<int:id>", imprimirFacturaRecibo, name = "factura_imprimir1"),
	
	path("facturas/imprimir_all/<str:f1>/<str:f2>", imprimirFacturaList, name = "facturas_imprimir_all"),

]

fac/models.py
from django.db import models
from bases.models import ClassModelo, ClassModelo2
from inv.models import Producto

#Para Utilizacion de Signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

# Create your models here.

"""docstring for Cliente"""
class Cliente(ClassModelo):
	NAT = "Natural"
	JUR = "Juridica"
	TIPO_CLIENTE = [
		(NAT, "Natural"),
		(JUR, "Juridica"),
	]
	nombres = models.CharField(max_length = 100)
	apellidos = models.CharField(max_length = 100)
	telefono = models.CharField(
		max_length = 20, 
		null=True,
		blank=True
	)
	tipo = models.CharField(
		max_length = 10,
		choices = TIPO_CLIENTE,
		default = NAT
	)

	def __str__(self):
		return "{} {}".format(self.apellidos, self.nombres)

	def save(self):
		self.nombres = self.nombres.upper()
		self.apellidos = self.apellidos.upper()
		super(Cliente, self).save()

	class Meta:
		verbose_name = 'Clientes'

class FacturaEnc(ClassModelo2):
	cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add = True)
	sub_total = models.FloatField(default = 0)
	descuento = models.FloatField(default = 0)
	total = models.FloatField(default = 0)

	def __str__(self):
		return "{}".format(self.id)

	def save(self):
		self.total = self.sub_total - self.descuento
		super(FacturaEnc, self).save()

	class Meta:
		verbose_name_plural = "Encabezado de Facturas"
		verbose_name = "Encabezado Factura"
		permissions = [
			("sup_caja_facturaenc", "Permisos de Supervisor de Caja Encabezado")
		]

class FacturaDet(ClassModelo2):
	factura = models.ForeignKey(FacturaEnc, on_delete = models.CASCADE)
	producto = models.ForeignKey(Producto, on_delete = models.CASCADE)
	cantidad = models.BigIntegerField(default = 0)
	precio = models.FloatField(default = 0)
	sub_total = models.FloatField(default = 0)
	descuento = models.FloatField(default = 0)
	total = models.FloatField(default = 0)

	def __str__(self):
		return "{}".format(self.producto)

	def save(self):
		self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
		self.total = self.sub_total - float(self.descuento)
		super(FacturaDet, self).save()

	class Meta:
		verbose_name_plural = "Detalles de Facturas"
		verbose_name = "Detalle Factura"
		permissions = [
			("sup_caja_facturadet", "Permisos de Supervisor de Caja Detalle")
		]

@receiver(post_save, sender = FacturaDet)
def detalleFacSave(sender, instance, **kwargs):
	factura_id = instance.factura.id
	producto_id = instance.producto.id

	encabezado = FacturaEnc.objects.get(pk = factura_id)

	if encabezado:
		sub_total = FacturaDet.objects.filter(factura = factura_id).aggregate(sub_total = Sum("sub_total")).get("sub_total", 0.00)

		descuento = FacturaDet.objects.filter(factura = factura_id).aggregate(sub_total = Sum("descuento")).get("descuento", 0.00)

		encabezado.sub_total = sub_total
		encabezado.descuento = descuento
		encabezado.save()

	prod = Producto.objects.filter(pk = producto_id).first()
	if prod:
		cantidad = int(prod.existencia) - int(instance.cantidad)
		prod.existencia = cantidad
		prod.save()

fac/forms.py
from django import forms

from .models import Cliente

"""docstring for ClienteForm"""
class ClienteForm(forms.ModelForm):
	class Meta:
		model = Cliente
		fields = [
			"nombres", "apellidos", "tipo", "telefono", "estado"
		]
		exclude = [
			"um", "fm", "uc", "fc"
		]

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.fields:
			self.fields[field].widget.attrs.update({
				"class" : "form-control"
			})

fac/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin #Aqui importamos un mixis
from django.views import generic #Para la manipulacion de diferentes tipos de vistas

from django.contrib.messages.views import SuccessMessageMixin # Para el mensaje success
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from datetime import datetime

from django.contrib import messages

from django.contrib.auth import authenticate

from bases.views import SinPrivilegios

from .models import Cliente, FacturaEnc, FacturaDet
from .forms import ClienteForm
from inv.views import ProductoView
from inv.models import Producto

# Create your views here.

"""docstring for ClienteView"""
class ClienteView(SinPrivilegios, generic.ListView):
	model = Cliente
	template_name = "fac/cliente_list.html"
	context_object_name = "obj"
	permission_required = "fac.view_cliente"

"""docstring for ViewBaseCreate"""
class ViewBaseCreate(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
	context_object_name ="obj"
	success_message = "Registro Agregado Correctamente!"

	def form_valid(self, form):
		form.instance.uc = self.request.user
		return super().form_valid(form)

"""docstring for ViewBaseEdit"""
class ViewBaseEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
	context_object_name ="obj"
	success_message = "Registro Actualizado Correctamente!"

	def form_valid(self, form):
		form.instance.um = self.request.user.id
		return super().form_valid(form)

"""docstring for ClienteCreate"""
class ClienteCreate(ViewBaseCreate):
	model = Cliente
	template_name = "fac/cliente_form.html"
	form_class = ClienteForm
	success_url = reverse_lazy("fac:cliente_list")
	permission_required = "fac.add_cliente"

"""docstring for ClienteUpdate"""
class ClienteUpdate(ViewBaseEdit):
	model = Cliente
	template_name = "fac/cliente_form.html"
	form_class = ClienteForm
	success_url = reverse_lazy("fac:cliente_list")
	permission_required = "fac.change_cliente"

@login_required(login_url = "/login/")
@permission_required("fac.change_cliente", login_url = "/login/")
def clienteDelete(request, id):
	cliente = Cliente.objects.filter(pk = id).first()

	if request.method == "POST":
		if cliente:			
			cliente.estado = not cliente.estado
			cliente.save()

			return HttpResponse("OK")
		else:
			return HttpResponse("FAIL")

	return HttpResponse("FAIL")


class FacturaView(SinPrivilegios, generic.ListView):
	model = FacturaEnc
	template_name = "fac/factura_list.html"
	context_object_name = "obj"
	permission_required = "fac.view_facturaenc"


@login_required(login_url = "/login/")
@permission_required("fac.change_facturaenc", login_url = "bases:sin_privilegios")
def facturas(request, id=None):
	template_name = "fac/facturas.html"

	detalle = {}
	clientes = Cliente.objects.filter(estado = True)

	if request.method == "GET":
		enc = FacturaEnc.objects.filter(pk=id).first()

		if not enc:
			encabezado = {
				"id" : 0,
				"fecha" : datetime.today(),
				"cliente" : 0,
				"sub_total" : 0.00,
				"total" : 0.00,
				"descuento": 0.00
			}

			detalle = None
		else:
			encabezado = {
				"id" : enc.id,
				"fecha" : enc.fecha,
				"cliente" : enc.cliente,
				"sub_total" : enc.sub_total,
				"total" : enc.total,
				"descuento": enc.descuento
			}

			detalle = FacturaDet.objects.filter(factura=enc)

		contexto = {
			"enc" : encabezado,
			"obj" : detalle,
			"clientes" : clientes
		}

	if request.method == "POST":
		cliente = request.POST.get("enc_cliente")
		fecha = request.POST.get("fecha")
		cli = Cliente.objects.get(pk=cliente)

		if not id:
			print("No existe id va a creat nuevo")
			print(cli)
			enc = FacturaEnc(
				cliente=cli,
				fecha=fecha,
			)
			print(enc)

			if enc:
				enc.save()
				id = enc.id
		elif id:			
			print("si existe va A filtrar")
			enc = FacturaEnc.objects.filter(pk = id).first()
			if enc:
				enc.cliente = cli
				enc.save()
		else:			
			print("No Tiene nada")
			messages.error(request, "No Se pudo Detectar el Nùmero de la Factura")
			return redirect("fac:factura_list")

		codigo = request.POST.get("codigo")
		cantidad = request.POST.get("cantidad")
		precio = request.POST.get("precio")
		sub_total = request.POST.get("sub_total_detalle")
		descuento = request.POST.get("descuento_detalle")
		total = request.POST.get("total_detalle")
		
		producto = Producto.objects.get(codigo=codigo)
		detalle = FacturaDet(
			factura = enc,
			producto = producto,
			cantidad = cantidad,
			precio = precio,
			sub_total = sub_total,
			descuento = descuento,
			total = total
		)

		if detalle:
			detalle.save()
			print("guardado con FacEnc")
			

		return redirect("fac:factura_edit", id = id)
	
	return render(request, template_name, contexto)


class FacProductoView(ProductoView):
	template_name = "fac/buscar_producto.html"

def borrarDetalleFactura(request, id = None):
	template_name = "fac/facturas_borrar_detalle.html"

	det = FacturaDet.objects.get(pk = id)

	if request.method == "GET":
		contexto = {
			"id" : id,
			"det" : det
		}
	if request.method == "POST":
		user = request.POST.get("usuario")
		pas = request.POST.get("password")

		usuario = authenticate(username = user, password = pas)
		if not usuario:
			return HttpResponse("Usuario o Clave Incorrecta!")

		if not usuario.is_active:
			return HttpResponse("Usuario Inactivo!")

		if usuario.is_superuser or usuario.has_perm("fac.sup_caja_facturadet"):
			det.id = None
			det.cantidad = (-1 * det.cantidad)
			det.sub_total = (-1 * det.sub_total)
			det.total = (-1 * det.total)
			det.descuento = (-1 * det.descuento)
			det.save()

			return HttpResponse("OK")

		return HttpResponse("Usuario No Autorizado!")

	return render(request,template_name,contexto)

fac/templates/fac/cliente_form.html
<div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">
		{% if obj %}
		<form method="post" role="form" class="form-inline" accept-charset="utf-8" action="{% url 'fac:cliente_edit' obj.pk %}">	
		{% else %}
		<form method="post" role="form" class="form-inline" accept-charset="utf-8" action="{% url 'fac:cliente_create' %}">		
		{% endif %}
			{% csrf_token %}
			<div class="col-xl-12 col-md-12 mb-6">
				{% if obj %} 
				<div class="card border-left-warning 
				shadow h-100 py-2">
				{% else %}
				<div class="card border-left-success 
				shadow h-100 py-2">
				{% endif %} 
					<div class="card-body">
						<div class="container no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-success text-uppercase mb-1">
									{% if obj %} Editar {% else %} Nueva {% endif %} 
									Cliente
								</div>
							</div>
							<hr class="sidebar-divider">
							<div class="row">						
								{{ form.as_p }}
							</div>
							<hr class="sidebar-divider">
							<div class="row text-center">
								<div class="col">
									<button type="submit" class="btn btn-primary"><li class="fa fa-save"></li> Guardar</button>
									<button class="btn btn-danger" type="button" onclick="return cerrar_modal()"><li class="fa fa-undo"></li> Cancelar</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

fac/templates/fac/facturas.html
{% extends "base/base.html" %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<div class="card shadow mb-4">
		<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
			<a href="#" class="btn btn-danger" title="Guardar">Guardar</a>
			<a href="{% url 'fac:factura_imprimir1' enc.id %}" class="btn btn-success" title="Imprimir" target="__factura">Imprimir</a>
			<a href="{% url 'fac:factura_list' %}" class="btn btn-info" title="Cancelar">Cancelar</a>		
		</div>
		<div class="card-body">
			<div class="content">
				<!-- Seccion Superior -->
				<div class="row">
					<!-- Seccion Izquierda -->
					<div class="col-lg-6">
						<div class="row">
							<div class="col-lg-12">
								<div class="row">
									<div class="col-lg-1">
										No.
									</div>
									<div class="col-lg-4">
										<input type="text" name="enc_id" id="enc_id" readonly="readonly" class="form-control">
									</div>
									<div class="col-lg-2">
										Cliente
									</div>
									<div class="col-lg-5 form-group">
										<select name="enc_cliente" id="enc_cliente" class="form-control">
											<option value="0"> Selecione Cliente</option>
											{% for cliente in clientes %}
												<option value="{{ cliente.id }}">{{ cliente.nombres }} {{ cliente.apellidos }}</option>
											{% endfor %}
										</select>
									</div>
								</div>

								<div class="row">
									<div class="col-lg-12 p-2">
										<div class="row">
											<div class="col-lg-6">
												fecha:
											</div>	
											<div class="col-lg-6">	
												Sub - Total:
											</div>	
										</div>
										<div class="row">
											<div class="col-lg-6">
												<input type="text" name="fecha" id="fecha" value="{{ enc.fecha | date:"Y-m-d" }}" readonly="readonly" class="form-control form-control-user">
											</div>	
											<div class="col-lg-6">	
												<input type="number" class="form-control text-right" value="0.00" readonly="readonly" name="sub_total" id="sub_total">
											</div>	
										</div>
										<div class="row">
											<div class="col-lg-12 text-right">
												Descuento:
											</div>
											<div class="col-lg-6 text-right">
											</div>
											<div class="col-lg-6 text-right">
												<input type="number" name="descuento" id="descuento" disabled="disabled" value="0.00" class="form-control text-right">
											</div>
											<div class="col-lg-12 text-right">
												Total:
											</div>
											<div class="col-lg-6 text-right">
											</div>
											<div class="col-lg-6 text-right">
												<input type="number" name="total" id="total" disabled="disabled" value="0.00" class="form-control text-right">
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>		
					</div>
					<!-- Seccion Derecha -->
					<div class="col-lg-6 form-group">
						<div class="row p-2">
							<div class="col-lg-2">
								Cod:
							</div>
							<div class="col-lg-3">
								<input type="text" class="form-control" name="codigo" id="codigo" placeholder="Cod. Producto">
							</div>
							<div class="col-lg-6">
								<input type="text" name="descripcion" id="descripcion" placeholder="Descripcion" disabled="disabled" class="form-control">
							</div>
							<div class="col-lg-1">
								<button type="button" class="btn btn-info" id="buscar"><li class="fas fa-search"></li></button>
							</div>
						</div>

						<div class="row">
							<div class="col-lg-2">
								Cant:
							</div>
							<div class="col-lg-3">
								<input type="number" name="cantidad" id="cantidad" placeholder="Cantidad" class="form-control">
							</div>
							<div class="col-lg-3">
								<input type="number" name="precio" id="precio" placeholder="Precio" readonly="readonly" class="form-control">
							</div>
							<div class="col-lg-3">
								<input type="number" name="descuento_detalle" id="descuento_detalle" placeholder="Descuento" class="form-control">
							</div>
							<div class="col-lg-1">
								<button type="submit" class="btn btn-danger" id="guardar"><li class="far fa-plus-square"></li></button>
							</div>
						</div>
						<div class="row p-1">
							<div class="col-lg-9 text-right">
								Sub - Total
							</div>
							<div class="col-lg-3">
								<input type="number" name="sub_total_detalle" id="sub_total_detalle" class="form-control" placeholder="Sub Total" value="0.00" disabled="disabled">
							</div>
						</div>
						<div class="row p-1">
							<div class="col-lg-9 text-right">
								Total
							</div>
							<div class="col-lg-3">
								<input type="number" name="total_detalle" id="total_detalle" class="form-control" placeholder="Total" value="0.00" disabled="disabled">
							</div>
						</div>
					</div>
				</div>
				<!-- Fin Seccion Superior -->
				<hr>
				<!-- Inicio de Detalles -->
				<div class="row p-1">
					<div class="col-lg-12">
						<table 
							data-toggle="table" 
							data-pagination="true" 
							data-search="true" 
							data-show-columns="true" 
							data-show-toggle="true" 
							data-show-fullscreen="true"
							data-toolbar=".buttons-toolbar">
							<thead>
								<tr>
									<th data-sortagle="true" data-field="id">Id.</th>
									<th data-sortagle="true" data-field="codigo">Código</th>
									<th data-sortagle="true" data-field="descripcion">Descripción</th>
									<th data-field="cantidad">Cantidad</th>
									<th data-field="sub_total">Sub - Total</th>
									<th data-field="descuento">Descuento</th>
									<th data-field="total">Total</th>
									<th class="all">Acciónes</th>
								</tr>
							</thead>
							<tbody>
								{% for item in obj %}
									<tr>
										<td>{{ item.id }}</td>
										<td>{{ item.producto }}</td>
										<td>{{ item.producto.descripcion }}</td>
										<td>{{ item.cantidad }}</td>
										<td>{{ item.sub_total }}</td>
										<td>{{ item.descuento }}</td>
										<td>{{ item.total }}</td>
										<td>
											<button type="button" class="btn btn-warning btn-circle" onclick="viewBorrarDetalle({{item.id}})"><li class="fas fa-history"></li></button>
										</td>
									</tr>								
								{% endfor %}
							</tbody>
						</table>
					</div>	
				</div>
				<!-- Fin Inicio de Detalles -->
			</div>
		</div>
	</div>	
</form>
{% endblock %}


{% block  js %}
<script type="text/javascript">

jQuery(document).ready(function($) {
	$("#sidebarToggle").click();
	$("#enc_cliente").select2({
		placeholder : "Selecione Cliente",
		allowClear : true
	});
	$("#buscar").click(function(e) {
		if ($("#enc_cliente").val() === "0") {
			alertify.error("Cliento No Seleionado!!");       
			return false;
		}
		abrir_modal("{% url 'fac:factura_producto' %}");
	});

	//chequiamos si  precionamos la tecla de enter
	$("#codigo").keypress(function(e) {
		if (e.keyCode === 13) {
			e.preventDefault();
			buscarProducto();
		}
	});

	$("#cantidad, #precio, #descuento_detalle").change(function(e) {
		calcularDetalle();
	});
	$("#enc_id").val("{{ enc.id }}");
	$("#enc_cliente").val("{{ enc.cliente }}").change();
	$("#fecha").val("{{ enc.fecha | date:'Y-m-d' }}");
	$("#sub_total").val("{{ enc.sub_total }}");
	$("#descuento").val("{{ enc.descuento }}");
	$("#descuento_detalle").val("{{ enc.total }}");
});

// Funcion para buscar el producto por el Codigo o por El Codigo de Barra
function buscarProducto() {
	//validamos si no esta vacio o es nulo
	if ($("#enc_cliente").val() === "0" || $("#enc_cliente").val() === null) {
		alertify.error("Cliento No Seleionado!!");       
		return false;
	}
	var codigo = $("#codigo").val();
	if (codigo === "") { //validamos sino esta vacio
		return false;
	}

	var path = "{% url 'api:producto_list' %}/" + codigo;
	$.ajax({
		type: "GET",
		url: path,
		success: function(res){
			console.log(res);
			console.log(res.existencia);
			console.log(res.estado);

			if (res.existencia <= 0 || !res.estado) {
				alertify.warning("Producto No Tiene Existencia o Inactivo!!");
				$("#codigo").val("");
				$("#descripcion").val("");
				$("#precio").val("");
				return false;  
			}
			//Agregamos los datos a los inputs
			$("#codigo").val(res.codigo);
			$("#descripcion").val(res.descripcion);
			$("#precio").val(res.precio);
			$("#codigo").val(res.codigo);

			$("#cantidad").focus();

		},
		error: function(jqXHR, textStatus, errorThow){
			console.log(jqXHR);
			//console.log(textStatus);
			//console.log(errorThow);
			//console.log(jqXHR.status);
			//console.log(jqXHR.responseText.detail);
			//jqXHR.responseText["detail"];
			//alertify.error(errorThow);

			//si da un error mostramos el mensaje y vaciamos los input
			if (jqXHR.status === 404) {
				alertify.error("Producto -"+ codigo +"- No Encontrado Ò No Existe");
				$("#codigo").val("");
				$("#descripcion").val("");
				$("#precio").val("0.00");
				$("#codigo").focus();
			}
				
		}
	});
}
function calcularDetalle() {
	var cantidad, precio, descuento, subTotal, total;

	cantidad = $("#cantidad").val();
	cantidad = cantidad === "" ? 0 : +cantidad;
	cantidad = cantidad < 0 ? 0 : cantidad;

	precio = $("#precio").val();
	precio = precio === "" ? 0 : +precio;
	precio = precio < 0 ? 0 : precio;

	descuento = $("#descuento_detalle").val();
	descuento = descuento === "" ? 0 : +descuento;
	descuento = descuento < 0 ? 0 : descuento;

	descuento = descuento  > (cantidad * precio) ? 0 : descuento;

	subTotal = cantidad * precio;
	total = subTotal - descuento;

	$("#cantidad").val(cantidad);
	$("#precio").val(precio);
	$("#descuento_detalle").val(descuento);
	$("#sub_total_detalle").val(subTotal);
	$("#total_detalle").val(total);

	console.log("Cantidad "+ cantidad);
	console.log("Precio "+ precio);
	console.log("descuento "+ descuento);

	console.log("Sub total detalle "+ subTotal);
	console.log("Total detalle "+ total);
}

function viewBorrarDetalle(id) {
	var url = "/fac/facturas/borrar_detalle/"+ id;
	//console.log(url);
	abrir_modal(url);
}

</script>
{% endblock %}

fac/templates/fac/facturas_borrar_detalle.html
<div class="modal-dialog modal-sm" role="document">
  <div class="modal-content text-center">
    <div class="modal-header">
      <h4 class="modal-title" id="title_modal">
        Confirmaciòn Requerida!
      </h4>
    </div>
    <div class="modal-body" id="body-modal">
      <label class="text-danger">¿Anular Producto <b>{{det.producto.descripcion}}</b>, Factura <b>{{det.factura.id}}</b>?</label>     
      <div class="form-group">
        <label for="usuario" class="control label">Usuario:</label>
        <input type="text" id="usuario" class="form-control" required="required" value="{{ user.username }}">
      </div>
      <div class="form-group">
        <label for="password" class="control label">Contraseña:</label>
        <input type="password" id="password" class="form-control" required="required" value="">
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-danger" id="borrar"><span class="far fa-trash-alt"></span> Borrar</button>
      <button class="btn btn-success" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" class="fas fa-times"></span> Cancelar</button>
    </div>
  </div><!-- /.modal-content -->    
</div><!-- /.modal-dialog -->

<script type="text/javascript">
  $(document).ready(function(e) {
    $("#borrar").click(function(e){
      e.preventDefault();
      var url = "{% url 'fac:factura_delete' id %}";
      var token = "{{ csrf_token }}";
      var data = {
        "usuario":$("#usuario").val(),
        "password":$("#password").val()
      };
      //data = JSON.stringify(data);
      console.log(data);

      $.ajax({
        headers : {"X-CSRFToken": token},
        type : "POST",
        url : url,
        data : data,
        success : function(resp){
          if (resp === "OK") {      
            location.reload(true);  
          } else{
            alertify.error(resp);
          }
        },
        error: function(jqXHR, textStatus, errorThow){
          alertify.error(errorThow);
          cerrar_modal();
        }
      });
    });
  });
</script>