api/urls.py
from django.urls import path, include

from . import views

urlpatterns = [	
	path("v1/productos", views.ProductoList.as_view(), name="producto_list"),
	path("v1/productos/<str:codigo>", views.ProductoDetalle.as_view(), name="producto_detalle"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path("categorias/", views.CategoriaView.as_view(), name = "categoria_list"),
	path("categorias/create", views.CategoriaCreate.as_view(), name = "categoria_create"),
	path("categorias/edit/<int:pk>", views.CategoriaUpdateView.as_view(), name = "categoria_edit"),
	path("categorias/delete/<int:pk>", views.CategoriaDeleteView.as_view(), name = "categoria_delete"),

	path("subcategorias/", views.SubCategoriaView.as_view(), name = "subcategoria_list"),
	path("subcategorias/create", views.SubCategoriaCreate.as_view(), name = "subcategoria_create"),
	path("subcategorias/edit/<int:pk>", views.SubCategoriaUpdateView.as_view(), name = "subcategoria_edit"),
	path("subcategorias/delete/<int:pk>", views.SubCategoriaDeleteView.as_view(), name = "subcategoria_delete"),

	path("marcas/", views.MarcaView.as_view(), name = "marca_list"),
	path("marcas/create", views.MarcaCreate.as_view(), name = "marca_create"),
	path("marcas/edit/<int:pk>", views.MarcaUpdateView.as_view(), name = "marca_edit"),
	path("marcas/inactivar/<int:id>", views.marca_inactivar, name = "marca_inactivar"),

	path("um/", views.UMView.as_view(), name = "um_list"),
	path("um/create", views.UMCreate.as_view(), name = "um_create"),
	path("um/edit/<int:pk>", views.UMUpdateView.as_view(), name = "um_edit"),
	path("um/inactivar/<int:id>", views.um_inactivar, name = "um_inactivar"),

	path("producto/", views.ProductoView.as_view(), name = "producto_list"),
	path("producto/create", views.ProductoCreate.as_view(), name = "producto_create"),
	path("producto/edit/<int:pk>", views.ProductoUpdateView.as_view(), name = "producto_edit"),
	path("producto/inactivar/<int:id>", views.producto_inactivar, name = "producto_inactivar"),

]

inv/forms.py
from django import forms #clase para la creacion de formularios

from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto #clase del modelo a utilizar

"""docstring for CategoriaForm"""
class CategoriaForm(forms.ModelForm):
	#aqui para modificar las propiedades
	class Meta:
		model = Categoria #decimos q modelo va utilizar
		fields =["descripcion", "estado"] #le cuales es el texto y nombre de lo campos
		labels = { #decimos q label va a utilizar cada uno aqui
			"descripcion" : "Descripcion de la categoria",
			"estado" : "Estado"
		}
		widget = { #aqui decimos q tipo de input va a ser
			"descripcion" : forms.TextInput()
		}

		#Aqui al inicializar le decimos q datos vamos a cambiar
		def __init__(self, *args, **kwargs):
		    super().__init__(*args, **kwargs)

		    #En este caso iteramos cada elemento para actualizar en este caso la class de cada input
		    for field in self.fields:
		    	self.fields[field].widget.attrs.update({
		    		"class" : "form-control"
		    	})

"""docstring for SubCategoriaForm"""
class SubCategoriaForm(forms.ModelForm):
	categoria = forms.ModelChoiceField(
		queryset = Categoria.objects.filter(estado=True).order_by("descripcion")
	)
	#aqui para modificar las propiedades
	class Meta:
		model = SubCategoria #decimos q modelo va utilizar
		fields = ["categoria","descripcion", "estado"] #le cuales es el texto y nombre de lo campos
		labels = { #decimos q label va a utilizar cada uno aqui
			"descripcion" : "Sub Categorias",
			"estado" : "Estado"
		}
		widget = { #aqui decimos q tipo de input va a ser
			"descripcion" : forms.TextInput
		}

		#Aqui al inicializar le decimos q datos vamos a cambiar
		def __init__(self, *args, **kwargs):
		    super().__init__(*args, **kwargs)

		    #En este caso iteramos cada elemento para actualizar en este caso la class de cada input
		    for field in self.fields:
		    	self.fields[field].widget.attrs.update({
		    		"class" : "form-control"
		    	})
		    self.fields["categoria"].empty_label = "Selecione Categoria"

"""docstring for MarcaForm"""
class MarcaForm(forms.ModelForm):
	#aqui para modificar las propiedades
	class Meta:
		model = Marca
		fields = ["descripcion", "estado"] #le cuales es el texto y nombre de lo campos
		labels = { #decimos q label va a utilizar cada uno aqui
			"descripcion" : "Descripcion de Marca",
			"estado" : "Estado"
		}
		widget = { #aqui decimos q tipo de input va a ser
			"descripcion" : forms.TextInput()
		}
	#Aqui al inicializar le decimos q datos vamos a cambiar
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		#En este caso iteramos cada elemento para actualizar en este caso la class de cada input
		for field in self.fields:
			self.fields[field].widget.attrs.update({
				"class" : "form-control"
			})

"""docstring for UMForm"""
class UMForm(forms.ModelForm):
	#aqui para modificar las propiedades
	class Meta:
		model = UnidadMedida
		fields = ["descripcion", "estado"] #le cuales es el texto y nombre de lo campos
		labels = { #decimos q label va a utilizar cada uno aqui
			"descripcion" : "Descripcion de Marca",
			"estado" : "Estado"
		}
		widget = { #aqui decimos q tipo de input va a ser
			"descripcion" : forms.TextInput()
		}
	#Aqui al inicializar le decimos q datos vamos a cambiar
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		#En este caso iteramos cada elemento para actualizar en este caso la class de cada input
		for field in self.fields:
			self.fields[field].widget.attrs.update({
				"class" : "form-control"
			})

"""docstring for ProductoForm"""
class ProductoForm(forms.ModelForm):
	class Meta:
		model = Producto
		fields = [
			"codigo",
			"codigo_barra",
			"descripcion", 
			"estado",
			"precio",
			"existencia", 
			"ultima_compra", 
			"marca", 
			"categoria", 
			"sub_categoria", 
			"unidad_medida"
		]
		exclude = ["um", "fm", "uc", "fc"] #Aqui excluimos algunos campos de no queremos q muestre
		widget = { #aqui decimos q tipo de input va a ser
			"descripcion" : forms.TextInput()
		}
		
	#Aqui al inicializar le decimos q datos vamos a cambiar
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		#En este caso iteramos cada elemento para actualizar en este caso la class de cada input
		for field in self.fields:
			self.fields[field].widget.attrs.update({
				"class" : "form-control"
			})
		self.fields["ultima_compra"].widget.attrs["readonly"] = True
		self.fields["existencia"].widget.attrs["readonly"] = True

inv/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin #Aqui importamos un mixis
from django.views import generic #Para la manipulacion de diferentes tipos de vistas
from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto

from django.urls import reverse_lazy #Clase para manitpulacion de url

from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UMForm, ProductoForm #Clase form a utilizar

#Modulos para la utilizar y crear mensajes para enviarselo a las vistas desde django
from django.contrib import messages #para los mensajes de las vistas basada en funciones
from django.contrib.messages.views import SuccessMessageMixin #para los mensajes de vistas basada en clases

from bases.views import SinPrivilegios

"""docstring for CategoriaView"""
class CategoriaView(SinPrivilegios, generic.ListView):
	permission_required = "inv.view_categoria"
	model = Categoria
	template_name = "inv/categoria_list.html"
	context_object_name = "obj"
	login_url = "bases:login"

"""docstring for CategoriaCreate"""
class CategoriaCreate(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):
	model = Categoria
	template_name = "inv/categoria_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = CategoriaForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:categoria_list") #Y cuando sea success a q url va
	success_message = "Categoria Creada con Existo" # Para el mixins de los mensaje(clases basada en vista)

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.uc = self.request.user
		return super().form_valid(form)

"""docstring for CategoriaUpdateView"""
class CategoriaUpdateView(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
	model = Categoria
	template_name = "inv/categoria_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = CategoriaForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:categoria_list") #Y cuando sea success a q url va
	success_message = "Categoria Actualizada" # Para el mixins de los mensaje(clases basada en vista)

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.um = self.request.user.id
		return super().form_valid(form)

"""docstring for CategoriaDeleteView"""
class CategoriaDeleteView(LoginRequiredMixin, generic.DeleteView):
	model = Categoria
	template_name = "inv/catalogos_Del.html"
	context_object_name = "obj"
	login_url = "bases:login"
	success_url = reverse_lazy("inv:categoria_list")

"""docstring for SubCategoriaView"""
class SubCategoriaView(SinPrivilegios, generic.ListView):
	permission_required = "inv.view_subcategoria"
	model = SubCategoria
	template_name = "inv/subcategoria_list.html"
	context_object_name = "obj"
	login_url = "bases:login"

"""docstring for SubCategoriaCreate"""
class SubCategoriaCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
	permission_required = "inv.view_subcategoria"
	model = SubCategoria
	template_name = "inv/subcategoria_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = SubCategoriaForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:subcategoria_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.uc = self.request.user
		return super().form_valid(form)

"""docstring for SubCategoriaUpdateView"""
class SubCategoriaUpdateView(LoginRequiredMixin, generic.UpdateView):
	model = SubCategoria
	template_name = "inv/subcategoria_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = SubCategoriaForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:subcategoria_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.um = self.request.user.id
		return super().form_valid(form)

"""docstring for SubCategoriaDeleteView"""
class SubCategoriaDeleteView(LoginRequiredMixin, generic.DeleteView):
	model = SubCategoria
	template_name = "inv/catalogos_Del.html"
	context_object_name = "obj"
	login_url = "bases:login"
	success_url = reverse_lazy("inv:subcategoria_list")

"""docstring for MarcaView"""
class MarcaView(SinPrivilegios, generic.ListView):
	permission_required = "inv.view_marca" #este metodo aqui q colocarlo porque lo tiene heredado de la class SinPrivilegios
	model = Marca
	template_name = "inv/marcas_list.html"
	context_object_name = "obj"
	login_url = "bases:login"

"""docstring for MarcaCreate"""
class MarcaCreate(LoginRequiredMixin, generic.CreateView):
	model = Marca
	template_name = "inv/marca_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = MarcaForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:marca_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.uc = self.request.user
		return super().form_valid(form)

"""docstring for MarcaUpdateView"""
class MarcaUpdateView(LoginRequiredMixin, generic.UpdateView):
	model = Marca
	template_name = "inv/marca_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = MarcaForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:marca_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.um = self.request.user.id
		return super().form_valid(form)

def marca_inactivar(request, id):
	marca = Marca.objects.filter(pk=id).first()
	contexto = {}
	template_name = "inv/catalogos_Del.html"

	if not marca:

		return redirect("inv:marca_list")

	elif request.method == "GET":
		contexto = {"obj":marca}

	elif request.method == "POST":
		marca.estado =  False
		marca.save()
		messages.warning(request, "Marca Inactivada")
		return redirect("inv:marca_list")

	return render(request,template_name,contexto)

"""docstring for UMView"""
class UMView(LoginRequiredMixin, generic.ListView):
	model = UnidadMedida
	template_name = "inv/um_list.html"
	context_object_name = "obj"
	login_url = "bases:login"

"""docstring for UMCreate"""
class UMCreate(LoginRequiredMixin, generic.CreateView):
	model = UnidadMedida
	template_name = "inv/um_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = UMForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:um_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.uc = self.request.user
		return super().form_valid(form)

"""docstring for UMUpdateView"""
class UMUpdateView(LoginRequiredMixin, generic.UpdateView):
	model = UnidadMedida
	template_name = "inv/um_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = UMForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:um_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.um = self.request.user.id
		return super().form_valid(form)

def um_inactivar(request, id):
	um = UnidadMedida.objects.filter(pk=id).first()
	contexto = {}
	template_name = "inv/catalogos_Del.html"

	if not um:

		return redirect("inv:um_list")

	elif request.method == "GET":
		contexto = {"obj":um}

	elif request.method == "POST":
		um.estado =  False
		um.save()
		return redirect("inv:um_list")

	return render(request,template_name,contexto)

"""docstring for Producto"""
class ProductoView(LoginRequiredMixin, generic.ListView):
	model = Producto
	template_name = "inv/producto_list.html"
	context_object_name = "obj"
	login_url = "bases:login"

"""docstring for ProductoCreate"""
class ProductoCreate(LoginRequiredMixin, generic.CreateView):
	model = Producto
	template_name = "inv/producto_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = ProductoForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:producto_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.uc = self.request.user
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(ProductoCreate, self).get_context_data(**kwargs)
		context["categorias"] = Categoria.objects.all()
		context["sub_categorias"] = SubCategoria.objects.all()
		return context

"""docstring for ProductoUpdateView"""
class ProductoUpdateView(LoginRequiredMixin, generic.UpdateView):
	model = Producto
	template_name = "inv/producto_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = ProductoForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("inv:producto_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.um = self.request.user.id
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		pk = self.kwargs.get("pk")

		context = super(ProductoUpdateView, self).get_context_data(**kwargs)
		context["categorias"] = Categoria.objects.all()
		context["sub_categorias"] = SubCategoria.objects.all()
		context["obj"] = Producto.objects.filter(pk=pk).first()

		return context

def producto_inactivar(request, id):
	producto = Producto.objects.filter(pk=id).first()
	contexto = {}
	template_name = "inv/catalogos_Del.html"

	if not producto:

		return redirect("inv:producto_list")

	elif request.method == "GET":
		contexto = {"obj":producto}

	elif request.method == "POST":
		producto.estado =  False
		producto.save()
		return redirect("inv:producto_list")

	return render(request,template_name,contexto)

inv/templates/inv/marca_list.html
{% extends "base/base.html" %}

{% block content %}
<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
	<h6 class="m-0 font-weight-bold text-primary">Listado de Marcas</h6>
	<div class="dropdown no-arrow">
		<a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
		</a>
		<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
			<div class="dropdown-header"></div>
			<a class="dropdown-item" href="{% url 'inv:marca_create' %}"><li class="fa fa-pluck"></li> Crear Nueva</a>
			<a class="dropdown-item" href="#"> <li class="fa fa-trash"></li> Ver papelera</a>
		</div>
	</div>
</div>
<div class="card-body">
	{% if not obj %}
		<div class="alert alert-info">
			No ay Marcas
		</div>
		{% else %}
		<table class="table table-hover table-striped" id="table">
			<thead>
				<tr>
					<th>Id</th>

					<th>Descripcion</th>

					<th>Estado</th>

					<th>F. Creado</th>

					<th>F. Modificado</th>

					<th class="all">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for marca in obj  %}
					<tr>
						<td>{{marca.id}}</td>
						<td>{{marca.descripcion}}</td>
						<td>{{marca.estado | yesno:'Activo,Inactivo'}}</td>
						<td>{{marca.fc | date:"d-m-Y"}}</td>
						<td>{{marca.fm | date:"d-m-Y"}}</td>
						<td>
							<a href="{% url 'inv:marca_edit' marca.id %}" title="Editar" class="btn btn-warning btn-circle" role="button"><li class="far fa-edit"></li></a>
							<a href="{% url 'inv:marca_inactivar' marca.id %}" title="Eliminar" class="btn btn-danger btn-circle" role="button"><li class="far fa-trash-alt"></li></a>
						</td>
					</tr>
				{% endfor %}			
			</tbody>
		</table>
	{% endif %}
</div>
{% endblock %}

{% block  js %}
<script type="text/javascript">
jQuery(document).ready(function($) {
	$("#table").DataTable();
});
</script>
{% endblock %}

inv/templates/inv/producto_list.html
{% extends "base/base.html" %}

{% block content %}
<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
	<h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
	<div class="dropdown no-arrow">
		<a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
		</a>
		<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
			<div class="dropdown-header"></div>
			<a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'inv:producto_create' %}')"><li class="fa fa-pluck"></li> Crear Nueva</a>
			<a class="dropdown-item" href="#"> <li class="fa fa-trash"></li> Ver papelera</a>
		</div>
	</div>
</div>
<div class="card-body">
	{% if not obj %}
		<div class="alert alert-info">
			No ay Productos
		</div>
		{% else %}
		<table class="table table-hover table-striped" id="table">
			<thead>
				<tr>
					<th>Sub - Categoria</th>

					<th>Código</th>

					<th>Codigo de Barra</th>

					<th>Descripción</th>

					<th>Existencia</th>

					<th>Marca</th>

					<th>Unidad Medida</th>

					<th>Estado</th>

					<th>F. Creado</th>

					<th class="all">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for producto in obj  %}
					<tr>
						<td>{{producto.sub_categoria}}</td>
						<td>{{producto.codigo}}</td>
						<td>{{producto.codigo_barra}}</td>
						<td>{{producto.descripcion}}</td>
						<td>{{producto.existencia}}</td>
						<td>{{producto.marca}}</td>
						<td>{{producto.unidad_medida}}</td>
						<td>{{producto.estado | yesno:'Activo,Inactivo'}}</td>
						<td>{{producto.fc | date:"d-m-Y"}}</td>
						<td>
							<a href="#" title="Editar" class="btn btn-warning btn-circle" role="button"  onclick="return abrir_modal('{% url 'inv:producto_edit' producto.id %}')"><li class="far fa-edit"></li></a>
							<a href="{% url 'inv:producto_inactivar' producto.id %}" title="Eliminar" class="btn btn-danger btn-circle" role="button"><li class="far fa-trash-alt"></li></a>
						</td>
					</tr>
				{% endfor %}			
			</tbody>
		</table>
	{% endif %}
</div>
{% endblock %}

{% block  js %}
<script type="text/javascript">
jQuery(document).ready(function($) {
	$("#table").DataTable();
});
</script>
{% endblock %}

inv/templates/inv/subcategoria_list.html
{% extends "base/base.html" %}

{% block content %}
<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
	<h6 class="m-0 font-weight-bold text-primary">Listado de Categoria</h6>
	<div class="dropdown no-arrow">
		<a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
		</a>
		<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
			<div class="dropdown-header"></div>
			<a class="dropdown-item" href="{% url 'inv:subcategoria_create' %}"><li class="fa fa-pluck"></li> Crear Nueva</a>
			<a class="dropdown-item" href="#"> <li class="fa fa-trash"></li> Ver papelera</a>
		</div>
	</div>
</div>
<div class="card-body">
	{% if not obj %}
		<div class="alert alert-info">
			No ay Sub-Categorias
		</div>
		{% else %}
		<table class="table table-hover table-striped" id="table">
			<thead>
				<tr>
					<th>Categoria</th>

					<th>Id</th>

					<th>Descripcion</th>

					<th>Estado</th>

					<th>F. Creado</th>

					<th>F. Modificado</th>

					<th class="all">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for subcategoria in obj  %}
					<tr>
						<td>{{subcategoria.categoria}}</td>
						<td>{{subcategoria.id}}</td>
						<td>{{subcategoria.id}}</td>
						<td>{{subcategoria.descripcion}}</td>
						<td>{{subcategoria.estado | yesno:'Activo,Inactivo'}}</td>
						<td>{{subcategoria.fc | date:"d-m-Y"}}</td>
						<td>{{subcategoria.fm | date:"d-m-Y"}}</td>
						<td>
							<a href="{% url 'inv:subcategoria_edit' subcategoria.id %}" title="Editar" class="btn btn-warning btn-circle" role="button"><li class="far fa-edit"></li></a>
							<a href="{% url 'inv:subcategoria_delete' subcategoria.id %}" title="Eliminar" class="btn btn-danger btn-circle" role="button"><li class="far fa-trash-alt"></li></a>
						</td>
					</tr>
				{% endfor %}			
			</tbody>
		</table>
	{% endif %}
</div>			
{% endblock %}

{% block  js %}
<script type="text/javascript">
jQuery(document).ready(function($) {
	$("#table").DataTable();
});
</script>
{% endblock %}

inv/templates/inv/um_list.html
{% extends "base/base.html" %}

{% block content %}
<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
	<h6 class="m-0 font-weight-bold text-primary">Listado de Unidades de Medidas</h6>
	<div class="dropdown no-arrow">
		<a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
		</a>
		<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
			<div class="dropdown-header"></div>
			<a class="dropdown-item" href="{% url 'inv:um_create' %}"><li class="fa fa-pluck"></li> Crear Nueva</a>
			<a class="dropdown-item" href="#"> <li class="fa fa-trash"></li> Ver papelera</a>
		</div>
	</div>
</div>
<div class="card-body">
	{% if not obj %}
		<div class="alert alert-info">
			No ay Unidades de Medidas
		</div>
		{% else %}
		<table class="table table-hover table-striped" id="table">
			<thead>
				<tr>
					<th>Id</th>

					<th>Descripcion</th>

					<th>Estado</th>

					<th>F. Creado</th>

					<th>F. Modificado</th>

					<th class="all">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for um in obj  %}
					<tr>
						<td>{{um.id}}</td>
						<td>{{um.descripcion}}</td>
						<td>{{um.estado | yesno:'Activo,Inactivo'}}</td>
						<td>{{um.fc | date:"d-m-Y"}}</td>
						<td>{{um.fm | date:"d-m-Y"}}</td>
						<td>
							<a href="{% url 'inv:um_edit' um.id %}" title="Editar" class="btn btn-warning btn-circle" role="button"><li class="far fa-edit"></li></a>
							<a href="{% url 'inv:um_inactivar' um.id %}" title="Eliminar" class="btn btn-danger btn-circle" role="button"><li class="far fa-trash-alt"></li></a>
						</td>
					</tr>
				{% endfor %}			
			</tbody>
		</table>
	{% endif %}
</div>
{% endblock %}

{% block  js %}
<script type="text/javascript">
jQuery(document).ready(function($) {
	$("#table").DataTable();
});
</script>
{% endblock %}