api/urls.py
from django.urls import path, include

from . import views

urlpatterns = [	
	path("v1/productos", views.ProductoList.as_view(), name="producto_list"),
	path("v1/productos/<str:codigo>", views.ProductoDetalle.as_view(), name="producto_detalle"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

cmp/urls.py
from django.urls import path, include

from . import views, reports

urlpatterns = [	
	path("proveedores/", views.ProveedorView.as_view(), name = "proveedor_list"),
	path("proveedores/create", views.ProveedorCreate.as_view(), name = "proveedor_create"),
	path("proveedores/edit/<int:pk>", views.ProveedorUpdateView.as_view(), name = "proveedor_edit"),
	path("proveedores/inactivar/<int:id>", views.proveedorDeleteView, name = "proveedor_inactivar"),

	path("compras/", views.ComprasView.as_view(), name = "compras_list"),
	path("compras/create", views.CreateCompra, name = "compras_create"),
	path("compras/edit/<int:id>", views.CreateCompra, name = "compras_edit"),
	path("compras/<int:compra_id>/delete/<int:pk>", views.CompraDetDelete.as_view(), name = "compras_delete"),

	path("compras/lists", reports.reporte_compras, name="compras_print_all"),
	path("compras/<int:compra_id>/imprimir", reports.imprimir_compra, name="compras_print_one"),
]

cmp/models.py
from django.db import models

from bases.models import ClassModelo

from inv.models import Producto

#Para Utilizacion de Signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

# Create your models here.

"""docstring for Proveedor"""
class Proveedor(ClassModelo):
	descripcion = models.CharField(
		max_length=100,
		unique=True
	)
	direccion = models.CharField(
		max_length=250,
		null=True,
		blank=True
	)
	contacto = models.CharField(
		max_length=10,
	)
	telefono = models.CharField(
		max_length=10,
		null=True,
		blank=True
	)
	email =  models.EmailField(
		null=True,
		blank=True
	)

	def __str__(self):
		return "{}".format(self.descripcion)

	def save(self):
		self.descripcion = self.descripcion.upper()
		super(Proveedor, self).save()

	class Meta:
		verbose_name='Proveedores'

"""docstring for CompraEnc"""
class CompraEnc(ClassModelo):
	fecha_compra = models.DateField(null = True, blank = True)
	observacion = models.TextField(null =  True, blank = True)
	no_factura = models.CharField(max_length = 100)
	fecha_factura = models.DateField()
	sub_total = models.FloatField(default = 0)
	descuento = models.FloatField(default = 0)
	total = models.FloatField(default = 0)

	proveedor = models.ForeignKey(Proveedor, on_delete = models.CASCADE)

	def __str__(self):
		return "{}".format(self.observacion)

	def save(self):
		self.observacion = self.observacion.upper()
		self.total = self.sub_total + self.descuento
		super(CompraEnc, self).save()

	class Meta:
		verbose_name_plural = "Encabezado de las Compras"
		verbose_name = "Encabezado de Compra"

"""docstring for CompraDet"""
class CompraDet(ClassModelo):
	compra = models.ForeignKey(CompraEnc, on_delete = models.CASCADE)
	producto = models.ForeignKey(Producto, on_delete = models.CASCADE)
	cantidad = models.BigIntegerField(default = 0)
	precio_prv = models.FloatField(default = 0)
	sub_total = models.FloatField(default = 0)
	descuento = models.FloatField(default = 0)
	total = models.FloatField(default = 0)
	costo = models.FloatField(default = 0)

	def __str__(self):
		return "{}".format(self.producto)

	def save(self):
		self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
		self.total = self.sub_total - float(self.descuento)
		super(CompraDet, self).save()

	class Meta:
		verbose_name_plural = "Detalles de las Compras"
		verbose_name = "Detalle Compra"


@receiver(post_delete, sender= CompraDet)
def detalleCompraDel(sender, instance, **kwargs):
	id_producto = instance.producto.id
	id_compra = instance.compra.id

	enc = CompraEnc.objects.filter(pk = id_compra).first()

	if enc:
		sub_total = CompraDet.objects.filter(compra = id_compra).aggregate(Sum("sub_total"))
		descuento = CompraDet.objects.filter(compra = id_compra).aggregate(Sum("descuento"))
		enc.sub_total = sub_total["sub_total__sum"] #Aqui ay q hacer un operador ternario porque cuando se None da un errorr
		enc.descuento = descuento["descuento__sum"] #Aqui ay q hacer un operador ternario porque cuando se None da un errorr

		enc.save()

	prod = Producto.objects.filter(pk = id_producto).first()
	if prod:
		cantidad = int(prod.existencia) - int(instance.cantidad)
		prod.existencia = cantidad
		prod.save()


@receiver(post_save, sender = CompraDet)
def detalleCompraSave(sender, instance, **kwargs):
	id_producto = instance.producto.id
	fecha_compra = instance.compra.fecha_compra

	prod = Producto.objects.filter(pk = id_producto).first()
	if prod:
		cantidad = int(prod.existencia) + int(instance.cantidad)
		prod.existencia = cantidad
		prod.ultima_compra = fecha_compra
		prod.save()

cmp/forms.py
from django import forms

from .models import Proveedor, CompraEnc

"""docstring for ProveedorForm"""
class ProveedorForm(forms.ModelForm):
	email = forms.EmailField(max_length=254)

	class Meta:
		model = Proveedor
		exclude = ["um", "fm", "uc", "fc"]
		widget = {
			"descripcion" : forms.TextInput()
		}
		
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.fields:
			self.fields[field].widget.attrs.update({
				"class" : "form-control"
			})

	def clean(self):
		try:
			sc = Proveedor.objects.get(
				descripcion = self.cleaned_data["descripcion"].upper()
			)
			if not self.instance.pk:
				print("Registro ya existe")
				raise forms.ValidationError("Registro ya existe!")
			elif self.instance.pk != sc.pk:
				print("Cambio no permitido")
				raise forms.ValidationError("Cambio no permitido!")
		except Proveedor.DoesNotExist:
			pass

		return self.cleaned_data

"""docstring for CompraEncForm"""
class CompraEncForm(forms.ModelForm):
	fecha_compra = forms.DateInput()
	fecha_factura = forms.DateInput()

	class Meta:
		model = CompraEnc
		fields = [
			"proveedor", "fecha_compra", "observacion",
			"no_factura", "fecha_factura", "sub_total",
			"descuento", "total"
		]

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.fields:
			self.fields[field].widget.attrs.update({
				"class" : "form-control"
			})

		self.fields["fecha_compra"].widget.attrs["readonly"] = True
		self.fields["fecha_factura"].widget.attrs["readonly"] = True
		self.fields["sub_total"].widget.attrs["readonly"] = True
		self.fields["descuento"].widget.attrs["readonly"] = True
		self.fields["total"].widget.attrs["readonly"] = True

cmp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin #Aqui importamos un mixis
from django.views import generic #Para la manipulacion de diferentes tipos de vistas

from django.urls import reverse_lazy #Clase para manitpulacion de url

from django.contrib.auth.decorators import login_required, permission_required

from .models import Proveedor, CompraEnc, CompraDet
from .forms import ProveedorForm, CompraEncForm

from bases.views import SinPrivilegios

from inv.models import Producto

from django.http import HttpResponse, JsonResponse
import json
import datetime
from django.db.models import Sum

"""docstring for MixinFormInvalid"""
class MixinFormInvalid:
	def form_invalid(self, form):
		response = super().form_invalid(form)
		if self.request.is_ajax():
			return JsonResponse(form.errors, status=400)
		else:
			return response


"""docstring for ProveedorView"""
class ProveedorView(LoginRequiredMixin, generic.ListView):
	model = Proveedor
	template_name = "cmp/proveedor_list.html"
	context_object_name = "obj"
	login_url = "bases:login"

"""docstring for ProveedorCreate"""
class ProveedorCreate(LoginRequiredMixin, MixinFormInvalid, generic.CreateView):
	model = Proveedor
	template_name = "cmp/proveedor_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = ProveedorForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("cmp:proveedor_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.uc = self.request.user
		return super().form_valid(form)

"""docstring for ProveedorUpdateView"""
class ProveedorUpdateView(LoginRequiredMixin, MixinFormInvalid, generic.UpdateView):
	model = Proveedor
	template_name = "cmp/proveedor_form.html"
	context_object_name = "obj"
	login_url = "bases:login"
	form_class = ProveedorForm #Aqui le indicamos a q formulario va
	success_url = reverse_lazy("cmp:proveedor_list") #Y cuando sea success a q url va

	#Reescribo el metodo de validacion
	def form_valid(self, form):
		form.instance.um = self.request.user.id
		return super().form_valid(form)

def proveedorDeleteView(request, id):
	template_name = "cmp/inactivar_prv.html"
	contexto = {}
	prv = Proveedor.objects.filter(pk=id).first()

	if not prv:
		return HttpResponse("Proveedor no Existe " + str(id))
	
	if request.method == "GET":
		contexto = {"obj" : prv}

	if request.method == "POST":
		prv.estado = False
		prv.save()
		contexto = {"obj" : "OK"}
		return HttpResponse("Proveedor Inactivado")

	return render(request, template_name, contexto)

"""docstring for ComprasView"""
class ComprasView(SinPrivilegios, generic.ListView):
	permission_required = "cmp.view_comprasenc"
	model = CompraEnc
	template_name = "cmp/compras_list.html"
	context_object_name = "obj"

@login_required(login_url = "login")
@permission_required("cmp.view_comprasenc", login_url = "bases:sinprivilegios")
def CreateCompra(request, id = None):
	template_name = "cmp/compras.html"
	productos = Producto.objects.filter(estado = True)
	form_compras = {}
	contexto = {}

	if request.method == "GET":
		form_compras = CompraEncForm()
		compraEnc = CompraEnc.objects.filter(pk = id).first()

		if compraEnc:
			compraDet = CompraDet.objects.filter(compra = compraEnc)
			fecha_compra = datetime.date.isoformat(compraEnc.fecha_compra)
			fecha_factura = datetime.date.isoformat(compraEnc.fecha_factura)

			datos = {
				"proveedor" : compraEnc.proveedor,
				"fecha_compra" : fecha_compra,
				"fecha_factura" : fecha_factura,
				"observacion" : compraEnc.observacion,
				"no_factura" : compraEnc.no_factura,
				"sub_total" : compraEnc.sub_total,
				"descuento" : compraEnc.descuento,
				"total" : compraEnc.total,
			}
			form_compras = CompraEncForm(datos)

		else:
			compraDet = None

		contexto = {
			"productos" : productos,
			"compraEnc" : compraEnc,
			"CompraDet" : compraDet,
			"form_compras" : form_compras
		}

	if request.method == "POST":
		fecha_compra = request.POST.get("fecha_compra");
		observacion = request.POST.get("observacion");
		no_factura = request.POST.get("no_factura");
		fecha_factura = request.POST.get("fecha_factura");
		proveedor = request.POST.get("proveedor");
		sub_total = 0
		descuento = 0
		total = 0

		if not id: 
			proveedor = Proveedor.objects.get(pk=proveedor);

			enc = CompraEnc(
				fecha_compra = fecha_compra,
				observacion = observacion,
				no_factura = no_factura,
				fecha_factura = fecha_factura,
				proveedor = proveedor,
				uc = request.user,
			)

			if enc:
				enc.save()
				id = enc.id
		else: 
			enc = CompraEnc.objects.filter(pk=id).first()

			if enc:
				enc.fecha_compra = fecha_compra
				enc.observacion = observacion
				enc.no_factura = no_factura
				enc.fecha_factura = fecha_factura
				enc.um = request.user.id
				enc.save()

		if not id:
			return redirect("cmp:compras_list")

		producto = request.POST.get("id_producto")
		cantidad = request.POST.get("id_cantidad_detalle")
		precio = request.POST.get("id_precio_detalle")
		sub_total_detalle = request.POST.get("id_sub_total_detalle")
		descuento_detalle = request.POST.get("id_descuento_detalle")
		total_detalle = request.POST.get("id_total_detalle")
		
		prod = Producto.objects.get(pk=producto)

		det = CompraDet(
			compra = enc,
			producto = prod,
			cantidad = cantidad,
			precio_prv = precio,
			descuento = descuento_detalle,
			costo = 0,
			uc = request.user
		)

		if det:
			det.save()

			sub_total = CompraDet.objects.filter(compra = id).aggregate(Sum("sub_total"))
			descuento = CompraDet.objects.filter(compra = id).aggregate(Sum("descuento"))

			enc.sub_total = sub_total["sub_total__sum"]
			enc.descuento = descuento["descuento__sum"]
			enc.save()

		return redirect("cmp:compras_edit", id = id)

	return render(request, template_name, contexto)


"""docstring for CompraDetDelete"""
class CompraDetDelete(SinPrivilegios, generic.DeleteView):
	permission_required = "cmp.delete_comprasdet"
	model = CompraDet
	template_name = "cmp/compras_det_del.html"
	context_object_name = "obj"

	def get_success_url(self):
		compra_id = self.kwargs["compra_id"]
		return reverse_lazy("cmp:compras_edit", kwargs = {
			"id" : compra_id
		})

cmp/templates/cmp/compras.html
{% extends "base/base.html" %}

{% block content %}
	<form method="post" accept-charset="utf-8" id="form_compras">
		{% csrf_token %}
		{% if compraEnc %}
		<div class="card border-left-warning shadow h-100 py-2">
		{% else %}
		<div class="card border-left-success shadow h-100 py-2">	
		{% endif %}	
			<div class="card-body">
				<div class="row no-getters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
							{% if compraEnc %} Editar {% else %} Nueva {% endif %}
							Compra
						</div>
						<hr>
						<div class="row">
							<div class="col-6">
								<div class="form-group row">
									<label for="" class="col-sm-2 col-form-label">Proveedor:</label>
									<div class="col-sm-10">
										{{ form_compras.proveedor }}
									</div>
								</div>
								<div class="row">
									<div class="col-6">
										<div class="form-group">
											<label for="fecha_compra">Fecha Compra:</label>
											<div class="fecha_compra">		
												
												{# <input type="date" name="fecha_compra" class="form-control" id="fecha_compra">#}{{ form_compras.fecha_compra }} 
											</div>
										</div>
										<div class="form-group">
											<label for="fecha_compra">Descripción:</label>
											{{ form_compras.observacion }}
										</div>
									</div>
									<div class="col-6">
										<div class="form-group">
											<label for="">Nro. Factura:</label>
											{{ form_compras.no_factura }}
										</div>
										<div class="form-group">
											<label for="">Fecha Factura:</label>
											<div class="fecha_factura">
												
												{# <input type="date" name="fecha_factura" class="form-control" id="fecha_factura">#}{{ form_compras.fecha_factura }}	
											</div>
										</div>
										<div class="row">
											<div class="col">
												<label for="sub_total">Sub Total</label>
												{{ form_compras.sub_total }}
											</div>
										</div>
										<div class="row">
											<div class="col">
												<label for="descuento">Descuento</label>
												{{ form_compras.descuento }}
											</div>
										</div>
										<div class="row">
											<div class="col">
												<label for="total">Total</label>
												{{ form_compras.total }}
											</div>
										</div>
									</div>
								</div>		
							</div>

							<div class="col-6">
								<div class="col">
									<table class="table table-striped table-hover dt-responsive nowrap" style="width: 100%;">
										<thead>
											<tr>
												<th>Id</th>
												<th class="all">Descripción</th>
												<th class="all">Acciones</th>
											</tr>
										</thead>
										<tbody>
											{% for producto in productos %}	
											<tr>
												<td>{{producto.id}}</td>
												<td>{{producto.descripcion}}</td>
												<td>
													<button type="button" class="btn btn-warning btn-circle"  onclick="selectProduct({{ producto.id }} , '{{ producto.descripcion }}')">+</button>
												</td>
											</tr>
											{% endfor %}
										</tbody>
									</table>
								</div>

								<div class="form-group row">
									<label for="id_producto" class="col-sm-3 col-form-label">Producto</label>
									<div class="col-sm-2">
										<input type="text" readonly name="id_producto" id="id_producto" class="form-control-plaintext" value="" required="required">
									</div>
									<div class="col-sm-2">
										<input type="text" readonly name="id_descripcion_producto" id="id_descripcion_producto" class="form-control-plaintext" value="" required="required">
									</div>
								</div>
								<div class="form-group row">
									<label for="id_cantidad_detalle" class="col-sm-3 col-form-label">Cant..:</label>
									<div class="col-sm-2">
										<input type="number" class="form-control" name="id_cantidad_detalle" id="id_cantidad_detalle" value="0" required="required">
									</div>	
									<label for="id_precio_detalle" class="col-sm-3 col-form-label">Precio</label>
									<div class="col-sm-2">
										<input type="number" class="form-control" name="id_precio_detalle" id="id_precio_detalle" value="0" required="required">
									</div>	
									<label for="id_descuento_detalle" class="col-sm-3 col-form-label">Desc..:</label>
									<div class="col-sm-2">
										<input type="text" class="form-control" name="id_descuento_detalle" id="id_descuento_detalle" value="0">
									</div>				
								</div>
								<div class="form-group row">
									<label for="id_sub_total_detalle" class="col-sm-3 col-form-label">S. Total:</label>
									<div class="col-sm-2">
										<input type="text" class="form-control-plaintext" name="id_sub_total_detalle" id="id_sub_total_detalle" value="0">
									</div>	
									<label for="id_total_detalle" class="col-sm-3 col-form-label">Total:</label>
									<div class="col-sm-2">
										<input type="text" class="form-control-plaintext col-sm-10" name="id_total_detalle" id="id_total_detalle" value="0">
									</div>
									<div class="col-sm-1">
										<button type="button" class="btn btn-sm col-sm-2" onclick="clearDetalle();">x</button>
									</div>
								</div>
								<hr>
								<div class="row">
									<div class="col">
										<button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
										<a href="{% url 'cmp:compras_list' %}" class="btn btn-success"> Cancelar</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>			

				<div class="row">
					<div class="col">
						<table class="table table-striped table-hover dt-responsive nowrap" style="width: 100%;">
							<thead>
								<tr>
									<th>Producto</th>
									<th>Cantidad</th>
									<th>Precio</th>
									<th>Sub Total</th>
									<th>Descuento</th>
									<th>Total</th>
									<th class="all">Acciones</th>
								</tr>
							</thead>
							<tbody>
								{% for detalle in CompraDet %}
								<tr>
									<td>{{detalle.producto}}</td>
									<td>{{detalle.cantidad}}</td>
									<td>{{detalle.precio_prv}}</td>
									<td>{{detalle.sub_total}}</td>
									<td>{{detalle.descuento}}</td>
									<td>{{detalle.total}}</td>
									<td>
										<button type="button" class="btn btn-danger btn.circle" onclick="return abrir_modal('{% url 'cmp:compras_delete' compraEnc.pk detalle.id %}');"><span class="fas fa-trash-alt"></span></button>
									</td>
								</tr>								
								{% endfor %}
							</tbody>
						</table>
					</div>						
				</div>		
		</div>
	</form>
{% endblock %}

{% block  js %}
<script type="text/javascript">
jQuery(document).ready(function($) {

	$("#sidebarToggle").click();

	$("#table").DataTable();

	jQuery.datetimepicker.setLocale("es");

	$("#id_fecha_compra, #id_fecha_factura").datetimepicker({
		format: "Y-m-d",
		timepicker: false
	});

	$("#id_cantidad_detalle, #id_precio_detalle, #id_descuento_detalle").change(function(){
		calcularDetalle();
	});

	$("#id_proveedor").focus();
	/* Valida Envio de formulario */
	$("#form_compras").submit(function(event) {
		if ($("#id_total_detalle").val() == 0 || $("id_producto").val() == 0) {
			event.preventDefault();
			alertify.warning("No AH Agregado Producto o Esta Sin Cantidades!!");     
		}
	});
	/* Fin de la Validacion de formulario */
});

function selectProduct(id, description){
	$("#id_cantidad_detalle").val(00);
	$("#id_precio_detalle").val(00);
	$("#id_descuento_detalle").val(00);

	$("#id_sub_total_detalle").val(00);
	$("#id_total_detalle").val(00);

	$("#id_producto").val(+id);
	$("#id_descripcion_producto").val(description);
	$("#id_cantidad_detalle").focus();
	$("#id_cantidad_detalle").select();

	$(".table").DataTable().search("").draw();	
}

function calcularDetalle() {
	var cantidad, precio, descuento, subTotal, total;
	//calculamos y validamos la cantidad
	cantidad = $("#id_cantidad_detalle").val();
	cantidad = cantidad === "" ? 0 : +cantidad;
	cantidad = cantidad < 0 ? 0 : cantidad;

	//calculamos y validamos el precio
	precio = $("#id_precio_detalle").val();
	precio = precio === "" ? 0 : +precio;
	precio = precio < 0 ? 0 : precio;

	//calculamos y validamos el descuento
	descuento = $("#id_descuento_detalle").val();
	descuento = descuento === "" ? 0 : +descuento;
	descuento = descuento < 0 ? 0 : descuento;

	//validamos si el descuento mayor q la cantidad por el precio  
	descuento = descuento > (cantidad * precio) ? 0 : descuento;

	//asignamos el subTotal y el total a las variables
	subTotal = cantidad * precio;
	total = subTotal - descuento;

	//Agregamos los valores a los inputs
	$("#id_cantidad_detalle").val(cantidad);
	$("#id_precio_detalle").val(precio);
	$("#id_descuento_detalle").val(descuento);

	$("#id_sub_total_detalle").val(subTotal);
	$("#id_total_detalle").val(total);
}

function clearDetalle(){
	$("#id_cantidad_detalle").val(00);
	$("#id_precio_detalle").val(00);
	$("#id_descuento_detalle").val(00);

	$("#id_sub_total_detalle").val(00);
	$("#id_total_detalle").val(00);

	$("#id_producto").val("");
	$("#id_descripcion_producto").val("");

	$(".table").DataTable().search("").draw();	

	$("#id_proveedor").focus();
}
</script>
{% endblock %}

cmp/templates/cmp/compras_det_del.html
<div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">
		<form role="form" action="{% url 'cmp:compras_delete' obj.compra_id obj.pk %}" method="post" accept-charset="utf-8" class="form-inline">
			<div class="col-xl-12 col-md-12 mb-12">
				<div class="card border-left danger shadow h-200 py-2">
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
									Eliminar Detalle
								</div>
								<hr>
								{% csrf_token %}
								<div class="row">
									Eliminar {{ obj }} de compra:&nbsp;<b>{{ obj.compra_id }}</b>
								</div>
								<hr>
								<div class="row">
									<div class="col">
										<button class="btn btn-danger" type="submit">
											<span class="fa fa-save"></span> Si, Eliminar
										</button>
										<button class="btn btn-success" type="button" onclick="return cerrar_modal();">
											<span class="fa fa-reload"></span>
											Cancelar
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>				
			</div>
		</form>
	</div>
</div>

cmp/templates/cmp/compras_list.html
{% extends "base/base.html" %}

{% block content %}
<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
	<h6 class="m-0 font-weight-bold text-primary">Listado de Compras</h6>
	<div class="dropdown no-arrow">
		<a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
		</a>
		<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
			<div class="dropdown-header"></div>
			<a class="dropdown-item" href="{% url 'cmp:compras_create' %}" title="Nueva"><li class="fas fa-pluck"></li> Crear Nueva</a>
			<a class="dropdown-item" href="{% url 'cmp:compras_print_all' %}" title="Listado" target="reportes"><li class="fa fa-print"></li> Listado</a>
			<a class="dropdown-item" href="#"> <li class="fa fa-trash"></li> Ver papelera</a>
		</div>
	</div>
</div>
<div class="card-body">
	{% if not obj %}
		<div class="alert alert-info">
			No ay Compras
		</div>
		{% else %}
		<table class="table table-hover table-striped" id="table">
			<thead>
				<tr>
					<th>id</th>

					<th>fecha</th>

					<th>Observación</th>

					<th>Nro. Factura</th>

					<th>Fecha Facturada</th>

					<th>Sub - Total</th>

					<th>Descuesto</th>

					<th>Total</th>

					<th>Estado</th>

					<th class="all">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for compra in obj  %}
					<tr>
						<td>{{compra.id}}</td>
						<td>{{compra.fecha_compra}}</td>
						<td>{{compra.observacion}}</td>
						<td>{{compra.no_factura}}</td>
						<td>{{compra.fecha_factura}}</td>
						<td>{{compra.sub_total}}</td>
						<td>{{compra.descuesto}}</td>
						<td>{{compra.total}}</td>
						<td>{{compra.estado | yesno:'Activo,Inactivo'}}</td>
						<td>
							<a href="{% url 'cmp:compras_edit' compra.id %}" title="Editar" class="btn btn-warning btn-circle" role="button"><li class="far fa-edit"></li></a>
							<a href="{% url 'cmp:compras_print_one' compra.id %}" title="Reporte" target="reportes" class="btn btn-success btn-circle" role="button"><li class="fas fa-print"></li></a>
						</td>
					</tr>
				{% endfor %}			
			</tbody>
		</table>
	{% endif %}
</div>
{% endblock %}

{% block  js %}
<script type="text/javascript">
jQuery(document).ready(function($) {

	$("#table").DataTable();
});
</script>
{% endblock %}